version: '3'
services:
  todofront:
   image: todofrontend
   depends_on:
    - todoback
   ports:
     - 3000:3000
   environment:
     - REACT_APP_API_HOST=todoback
   restart: always
  todoback:
   image: todobackend
   ports:
     - 3001:3001
   restart: always
  todotests:
   image: todotests
   depends_on:
     - todofront
     - todoback
   restart: always
   environment:
     - FRONT_HOST=todofront