version: '3'
services:
  frontend:
   build: front-end/
   restart: on-failure
   ports:
     - 3000:3000
   depends_on:
      - database
  backend:
   build: back-end/
   restart: on-failure
   ports:
     - 3001:3001
   environment:
      - DB_HOST=database
   depends_on:
      - database
  database:
   image: 
   restart: on-failure